In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv(r'D:\AI-Drug\DDI\decagon-master\bio-decagon-combo.csv')
data

,STITCH 1,STITCH 2,Polypharmacy Side Effect,Side Effect Name
0,CID000002173,CID000003345,C0151714,hypermagnesemia
1,CID000002173,CID000003345,C0035344,retinopathy of prematurity
2,CID000002173,CID000003345,C0004144,atelectasis
3,CID000002173,CID000003345,C0002063,alkalosis
4,CID000002173,CID000003345,C0004604,Back Ache
...,...,...,...,...
4649436,CID000003461,CID000003954,C0149871,deep vein thromboses
4649437,CID000003461,CID000003954,C0035410,rhabdomyolysis
4649438,CID000003461,CID000003954,C0043096,loss of weight
4649439,CID000003461,CID000003954,C0003962,ascites
4649440,CID000003461,CID000003954,C0038999,bulging

In [3]:
data.rename(columns={'Polypharmacy Side Effect': 'Polypharmacy_Side_Effect'}, inplace=True)
data

,STITCH 1,STITCH 2,Polypharmacy_Side_Effect,Side Effect Name
0,CID000002173,CID000003345,C0151714,hypermagnesemia
1,CID000002173,CID000003345,C0035344,retinopathy of prematurity
2,CID000002173,CID000003345,C0004144,atelectasis
3,CID000002173,CID000003345,C0002063,alkalosis
4,CID000002173,CID000003345,C0004604,Back Ache
...,...,...,...,...
4649436,CID000003461,CID000003954,C0149871,deep vein thromboses
4649437,CID000003461,CID000003954,C0035410,rhabdomyolysis
4649438,CID000003461,CID000003954,C0043096,loss of weight
4649439,CID000003461,CID000003954,C0003962,ascites
4649440,CID000003461,CID000003954,C0038999,bulging

In [4]:
drug=pd.read_csv(r'C:\Users\Zhouhaifan\Desktop\drug.csv')
drug

           STITCH      cid                                              smile
0    CID000060198    60198  C[C@]12CC[C@H]3[C@H]([C@@H]1CCC2=O)CC(=C)C4=CC...
1    CID000005152     5152   C1=CC=C(C=C1)CCCCOCCCCCCNCC(C2=CC(=C(C=C2)O)CO)O
2    CID000002576     2576                     CCCC(C)(COC(=O)N)COC(=O)NC(C)C
3    CID003085017  3085017                                   C=CCN.C1C(O1)CCl
4    CID000003657     3657                                         C(=O)(N)NO
..            ...      ...                                                ...
640  CID000001071     1071             CC1=C(C(CCC1)(C)C)C=CC(=CC=CC(=CCO)C)C
641  CID000005358     5358             CNS(=O)(=O)CC1=CC2=C(C=C1)NC=C2CCN(C)C
642  CID000002803     2803                       C1CN=C(N1)NC2=C(C=CC=C2Cl)Cl
643  CID000000853      853  C1=C(C=C(C(=C1I)OC2=CC(=C(C(=C2)I)O)I)I)CC(C(=...
644  CID000443871   443871  CC(C)[C@H]1CCC[C@@H](C1)C(=O)N[C@H](CC2=CC=CC=...

[645 rows x 3 columns]

In [5]:
import rdkit
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem.EState import Fingerprinter
from rdkit.Chem import MACCSkeys
fingerprint_list=[]
for j in drug['smile']:
    j1= Chem.MolFromSmiles(j)
    MACCS_fingerprint = MACCSkeys.GenMACCSKeys(j1)
    fingerprint_list.append(MACCS_fingerprint.ToBitString())
drug['MACCS_fingerprint']=fingerprint_list
drug

,STITCH,cid,smile,MACCS_fingerprint
0,CID000060198,60198,C[C@]12CC[C@H]3[C@H]([C@@H]1CCC2=O)CC(=C)C4=CC...,0000000000000000000000000010000000100000000000...
1,CID000005152,5152,C1=CC=C(C=C1)CCCCOCCCCCCNCC(C2=CC(=C(C=C2)O)CO)O,0000000000000000000000000000000000000000000000...
2,CID000002576,2576,CCCC(C)(COC(=O)N)COC(=O)NC(C)C,0000000000000000000000010000000000000000000000...
3,CID003085017,3085017,C=CCN.C1C(O1)CCl,0000000000000000100000100000000000100000000000...
4,CID000003657,3657,C(=O)(N)NO,0000000000000000000000001000000000000100000100...
...,...,...,...,...
640,CID000001071,1071,CC1=C(C(CCC1)(C)C)C=CC(=CC=CC(=CCO)C)C,0000000000000000000000000000000000000000000000...
641,CID000005358,5358,CNS(=O)(=O)CC1=CC2=C(C=C1)NC=C2CCN(C)C,0000000000000000000000000000000011000000000000...
642,CID000002803,2803,C1CN=C(N1)NC2=C(C=CC=C2Cl)Cl,0000000000000000000000000100000000000000000100...
643,CID000000853,853,C1=C(C=C(C(=C1I)OC2=CC(=C(C(=C2)I)O)I)I)CC(C(=...,0000000000000000000000000001000000000000000000...
644,CID000443871,443871,CC(C)[C@H]1CCC[C@@H](C1)C(=O)N[C@H](CC2=CC=CC=...,0000000000000000000000000000000000000000000000...

In [6]:
#str to int
def trans_str_to_int(fingerprint_str):
    int_list=[]
    for ii in fingerprint_str:
        ii=int(ii)
        int_list.append(ii)
    return int_list
MACCS_fingerprint_list=[]
for s in drug['MACCS_fingerprint']:
    s1=trans_str_to_int(s)
    MACCS_fingerprint_list.append(s1)
drug['MACCS_fingerprint_int']=MACCS_fingerprint_list
drug

,STITCH,cid,smile,MACCS_fingerprint,MACCS_fingerprint_int
0,CID000060198,60198,C[C@]12CC[C@H]3[C@H]([C@@H]1CCC2=O)CC(=C)C4=CC...,0000000000000000000000000010000000100000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,CID000005152,5152,C1=CC=C(C=C1)CCCCOCCCCCCNCC(C2=CC(=C(C=C2)O)CO)O,0000000000000000000000000000000000000000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
2,CID000002576,2576,CCCC(C)(COC(=O)N)COC(=O)NC(C)C,0000000000000000000000010000000000000000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,CID003085017,3085017,C=CCN.C1C(O1)CCl,0000000000000000100000100000000000100000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,CID000003657,3657,C(=O)(N)NO,0000000000000000000000001000000000000100000100...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
...,...,...,...,...,...
640,CID000001071,1071,CC1=C(C(CCC1)(C)C)C=CC(=CC=CC(=CCO)C)C,0000000000000000000000000000000000000000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
641,CID000005358,5358,CNS(=O)(=O)CC1=CC2=C(C=C1)NC=C2CCN(C)C,0000000000000000000000000000000011000000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
642,CID000002803,2803,C1CN=C(N1)NC2=C(C=CC=C2Cl)Cl,0000000000000000000000000100000000000000000100...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
643,CID000000853,853,C1=C(C=C(C(=C1I)OC2=CC(=C(C(=C2)I)O)I)I)CC(C(=...,0000000000000000000000000001000000000000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
644,CID000443871,443871,CC(C)[C@H]1CCC[C@@H](C1)C(=O)N[C@H](CC2=CC=CC=...,0000000000000000000000000000000000000000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [7]:
Side_Effect_count=data['Polypharmacy_Side_Effect'].value_counts()
Side_Effect_count

C0020649    28568
C0002871    27006
C0013404    26037
C0027497    25190
C0032285    24430
            ...
C0014935        2
C0011593        2
C0162678        2
C0013336        2
C0034494        1
Name: Polypharmacy_Side_Effect, Length: 1317, dtype: int64

In [8]:
Side_Effect_count_list=Side_Effect_count.index.tolist()
Side_Effect_count_list_800_1000=Side_Effect_count_list[800:1000]

In [9]:
data_800_1000=data[data.Polypharmacy_Side_Effect.isin(Side_Effect_count_list_800_1000)]
data_800_1000

,STITCH 1,STITCH 2,Polypharmacy_Side_Effect,Side Effect Name
10,CID000002173,CID000003345,C0038000,rupture of spleen
21,CID000002173,CID000003345,C0236124,Gastrointestinal Obstruction
34,CID000002173,CID000003345,C0035220,neonatal respiratory distress syndrome
55,CID000002173,CID000003345,C0013274,patent ductus arteriosis
175,CID000001302,CID000005064,C0155540,ear discharge
...,...,...,...,...
4649124,CID000003075,CID000003339,C0341047,parotid gland enlargement
4649143,CID000003075,CID000003339,C0040425,tonsillitis
4649307,CID000002477,CID000002541,C0020619,hypogonadism
4649315,CID000002477,CID000002541,C0003044,animal bite
4649387,CID000003461,CID000003954,C0206063,radiation pneumonitis

In [10]:
list2 = data_800_1000["STITCH 1"].values.tolist()
dict(zip(*np.unique(list2, return_counts=True)))
len(dict(zip(*np.unique(list2, return_counts=True))))

566

In [11]:
list3 = data_800_1000["STITCH 2"].values.tolist()
dict(zip(*np.unique(list3, return_counts=True)))
len(dict(zip(*np.unique(list3, return_counts=True))))

596

In [12]:
list4=list2+list3
dict1=dict(zip(*np.unique(list4, return_counts=True)))
len(dict(zip(*np.unique(list4, return_counts=True))))

620

故top800_top1000共计有620种药物，以及132364种药物相互作用

In [13]:
drug_800_1000=drug[drug.STITCH.isin(list4)]
drug_800_1000

,STITCH,cid,smile,MACCS_fingerprint,MACCS_fingerprint_int
0,CID000060198,60198,C[C@]12CC[C@H]3[C@H]([C@@H]1CCC2=O)CC(=C)C4=CC...,0000000000000000000000000010000000100000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,CID000005152,5152,C1=CC=C(C=C1)CCCCOCCCCCCNCC(C2=CC(=C(C=C2)O)CO)O,0000000000000000000000000000000000000000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
2,CID000002576,2576,CCCC(C)(COC(=O)N)COC(=O)NC(C)C,0000000000000000000000010000000000000000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,CID003085017,3085017,C=CCN.C1C(O1)CCl,0000000000000000100000100000000000100000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,CID000003657,3657,C(=O)(N)NO,0000000000000000000000001000000000000100000100...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
...,...,...,...,...,...
640,CID000001071,1071,CC1=C(C(CCC1)(C)C)C=CC(=CC=CC(=CCO)C)C,0000000000000000000000000000000000000000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
641,CID000005358,5358,CNS(=O)(=O)CC1=CC2=C(C=C1)NC=C2CCN(C)C,0000000000000000000000000000000011000000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
642,CID000002803,2803,C1CN=C(N1)NC2=C(C=CC=C2Cl)Cl,0000000000000000000000000100000000000000000100...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
643,CID000000853,853,C1=C(C=C(C(=C1I)OC2=CC(=C(C(=C2)I)O)I)I)CC(C(=...,0000000000000000000000000001000000000000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
644,CID000443871,443871,CC(C)[C@H]1CCC[C@@H](C1)C(=O)N[C@H](CC2=CC=CC=...,0000000000000000000000000000000000000000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [14]:
#修改行名称
index_update=np.arange(0,620)
drug_800_1000.index=index_update
drug_800_1000

,STITCH,cid,smile,MACCS_fingerprint,MACCS_fingerprint_int
0,CID000060198,60198,C[C@]12CC[C@H]3[C@H]([C@@H]1CCC2=O)CC(=C)C4=CC...,0000000000000000000000000010000000100000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,CID000005152,5152,C1=CC=C(C=C1)CCCCOCCCCCCNCC(C2=CC(=C(C=C2)O)CO)O,0000000000000000000000000000000000000000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
2,CID000002576,2576,CCCC(C)(COC(=O)N)COC(=O)NC(C)C,0000000000000000000000010000000000000000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,CID003085017,3085017,C=CCN.C1C(O1)CCl,0000000000000000100000100000000000100000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,CID000003657,3657,C(=O)(N)NO,0000000000000000000000001000000000000100000100...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
...,...,...,...,...,...
615,CID000001071,1071,CC1=C(C(CCC1)(C)C)C=CC(=CC=CC(=CCO)C)C,0000000000000000000000000000000000000000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
616,CID000005358,5358,CNS(=O)(=O)CC1=CC2=C(C=C1)NC=C2CCN(C)C,0000000000000000000000000000000011000000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
617,CID000002803,2803,C1CN=C(N1)NC2=C(C=CC=C2Cl)Cl,0000000000000000000000000100000000000000000100...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
618,CID000000853,853,C1=C(C=C(C(=C1I)OC2=CC(=C(C(=C2)I)O)I)I)CC(C(=...,0000000000000000000000000001000000000000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
619,CID000443871,443871,CC(C)[C@H]1CCC[C@@H](C1)C(=O)N[C@H](CC2=CC=CC=...,0000000000000000000000000000000000000000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [15]:
drug_800_1000['drug_ID']=index_update
drug_800_1000

C:\Users\Zhouhaifan\.conda\envs\py37\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,STITCH,cid,smile,MACCS_fingerprint,MACCS_fingerprint_int,drug_ID
0,CID000060198,60198,C[C@]12CC[C@H]3[C@H]([C@@H]1CCC2=O)CC(=C)C4=CC...,0000000000000000000000000010000000100000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0
1,CID000005152,5152,C1=CC=C(C=C1)CCCCOCCCCCCNCC(C2=CC(=C(C=C2)O)CO)O,0000000000000000000000000000000000000000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1
2,CID000002576,2576,CCCC(C)(COC(=O)N)COC(=O)NC(C)C,0000000000000000000000010000000000000000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",2
3,CID003085017,3085017,C=CCN.C1C(O1)CCl,0000000000000000100000100000000000100000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",3
4,CID000003657,3657,C(=O)(N)NO,0000000000000000000000001000000000000100000100...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",4
...,...,...,...,...,...,...
615,CID000001071,1071,CC1=C(C(CCC1)(C)C)C=CC(=CC=CC(=CCO)C)C,0000000000000000000000000000000000000000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",615
616,CID000005358,5358,CNS(=O)(=O)CC1=CC2=C(C=C1)NC=C2CCN(C)C,0000000000000000000000000000000011000000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",616
617,CID000002803,2803,C1CN=C(N1)NC2=C(C=CC=C2Cl)Cl,0000000000000000000000000100000000000000000100...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",617
618,CID000000853,853,C1=C(C=C(C(=C1I)OC2=CC(=C(C(=C2)I)O)I)I)CC(C(=...,0000000000000000000000000001000000000000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",618
619,CID000443871,443871,CC(C)[C@H]1CCC[C@@H](C1)C(=O)N[C@H](CC2=CC=CC=...,0000000000000000000000000000000000000000000000...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",619

In [16]:
drug_key_list=drug_800_1000['STITCH']
drug_value_list=drug_800_1000['drug_ID']
drug_dict = dict(zip(drug_key_list,drug_value_list))

In [17]:
STITCH_1_list=[]
for p in data_800_1000['STITCH 1']:
    q=drug_dict[p]
    STITCH_1_list.append(q)
data_800_1000['STITCH_1_ID']=STITCH_1_list
data_800_1000

C:\Users\Zhouhaifan\.conda\envs\py37\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

,STITCH 1,STITCH 2,Polypharmacy_Side_Effect,Side Effect Name,STITCH_1_ID
10,CID000002173,CID000003345,C0038000,rupture of spleen,545
21,CID000002173,CID000003345,C0236124,Gastrointestinal Obstruction,545
34,CID000002173,CID000003345,C0035220,neonatal respiratory distress syndrome,545
55,CID000002173,CID000003345,C0013274,patent ductus arteriosis,545
175,CID000001302,CID000005064,C0155540,ear discharge,181
...,...,...,...,...,...
4649124,CID000003075,CID000003339,C0341047,parotid gland enlargement,450
4649143,CID000003075,CID000003339,C0040425,tonsillitis,450
4649307,CID000002477,CID000002541,C0020619,hypogonadism,339
4649315,CID000002477,CID000002541,C0003044,animal bite,339
4649387,CID000003461,CID000003954,C0206063,radiation pneumonitis,18

In [18]:
STITCH_2_list=[]
for p in data_800_1000['STITCH 2']:
    q=drug_dict[p]
    STITCH_2_list.append(q)
data_800_1000['STITCH_2_ID']=STITCH_2_list
data_800_1000

C:\Users\Zhouhaifan\.conda\envs\py37\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

,STITCH 1,STITCH 2,Polypharmacy_Side_Effect,Side Effect Name,STITCH_1_ID,STITCH_2_ID
10,CID000002173,CID000003345,C0038000,rupture of spleen,545,82
21,CID000002173,CID000003345,C0236124,Gastrointestinal Obstruction,545,82
34,CID000002173,CID000003345,C0035220,neonatal respiratory distress syndrome,545,82
55,CID000002173,CID000003345,C0013274,patent ductus arteriosis,545,82
175,CID000001302,CID000005064,C0155540,ear discharge,181,533
...,...,...,...,...,...,...
4649124,CID000003075,CID000003339,C0341047,parotid gland enlargement,450,194
4649143,CID000003075,CID000003339,C0040425,tonsillitis,450,194
4649307,CID000002477,CID000002541,C0020619,hypogonadism,339,17
4649315,CID000002477,CID000002541,C0003044,animal bite,339,17
4649387,CID000003461,CID000003954,C0206063,radiation pneumonitis,18,215

In [19]:
Polypharmacy_Side_Effect_list=data_800_1000['Polypharmacy_Side_Effect'].values.tolist()
Side_Effect_Name_list=data_800_1000['Side Effect Name'].values.tolist()
id_name_dict = dict(zip(Polypharmacy_Side_Effect_list,Side_Effect_Name_list))
len(id_name_dict)

200

In [20]:
list6=data_800_1000['Polypharmacy_Side_Effect'].values.tolist()
list6_unqiue = []
for el in list6:
    if list6_unqiue.count(el) < 1:
        list6_unqiue.append(el)
DDI_list=list6_unqiue
len(DDI_list)
print(DDI_list)

['C0038000', 'C0236124', 'C0035220', 'C0013274', 'C0155540', 'C0027092', 'C0040485', 'C0152169', 'C0042164', 'C0007860', 'C0007868', 'C0033038', 'C0038012', 'C0038019', 'C1384606', 'C0003708', 'C0003635', 'C0002726', 'C0262414', 'C0001126', 'C0206504', 'C0021099', 'C0178428', 'C0027022', 'C0149925', 'C0426636', 'C0019917', 'C0005687', 'C0235761', 'C0018818', 'C0740858', 'C0003044', 'C0037578', 'C0032633', 'C0206063', 'C0232943', 'C0271468', 'C0242172', 'C0235660', 'C0006012', 'C0018500', 'C0022572', 'C0600327', 'C0152021', 'C0009375', 'C0085661', 'C0149741', 'C0020514', 'C0281774', 'C1527407', 'C0221166', 'C0242225', 'C0085652', 'C0033845', 'C0086438', 'C0271429', 'C0151514', 'C0040584', 'C0042870', 'C0037995', 'C0026919', 'C0030583', 'C0085583', 'C0021092', 'C0009410', 'C0040456', 'C0011633', 'C0002736', 'C0151620', 'C0002884', 'C0259749', 'C0010034', 'C0019284', 'C0039483', 'C0031538', 'C0002963', 'C0001175', 'C0006105', 'C0030354', 'C0152013', 'C0151971', 'C0011630', 'C0042961', 'C0008312', 'C0476427', 'C0262365', 'C0032305', 'C0750876', 'C0156181', 'C1510471', 'C0020258', 'C0007462', 'C0270629', 'C0282005', 'C0038833', 'C0025061', 'C0034372', 'C0006152', 'C0039446', 'C0027822', 'C1258666', 'C0016470', 'C0085166', 'C0019572', 'C0042907', 'C0302592', 'C0332687', 'C0262578', 'C0022568', 'C0016665', 'C0007078', 'C0341163', 'C0006846', 'C0025297', 'C0205929', 'C0020252', 'C0027430', 'C0042134', 'C0156369', 'C0040425', 'C0034880', 'C0033117', 'C0043145', 'C0238154', 'C0035302', 'C0027858', 'C0009088', 'C0026948', 'C0085662', 'C0040147', 'C0019357', 'C0019693', 'C0029936', 'C0021345', 'C0025637', 'C0079102', 'C0024198', 'C0024110', 'C0013369', 'C0241353', 'C0032273', 'C0190211', 'C0152459', 'C0010043', 'C0235267', 'C0030326', 'C0574960', 'C0040586', 'C0001816', 'C0085786', 'C0029124', 'C0024894', 'C0259817', 'C0281839', 'C0016479', 'C0034888', 'C0018843', 'C0026780', 'C0243010', 'C0221247', 'C0025160', 'C0029089', 'C0018924', 'C0015645', 'C0027932', 'C0014743', 'C0040259', 'C0020619', 'C0521620', 'C0009326', 'C0019159', 'C0039591', 'C0235328', 'C0341047', 'C0014534', 'C0008049', 'C0006271', 'C0009193', 'C0013390', 'C0010032', 'C0028077', 'C1621958', 'C1261473', 'C0024282', 'C0023241', 'C0015300', 'C0476089', 'C0276143', 'C0032310', 'C0004095', 'C0014175', 'C0026975', 'C0033046', 'C0038013', 'C0017605', 'C0016412', 'C0040145', 'C0020490', 'C0004690', 'C0005967']

In [21]:
edge_encoding=np.eye(200).tolist()
edgetype_key_list=DDI_list
edgetype_value_list=edge_encoding
edgetype_dict = dict(zip(edgetype_key_list,edgetype_value_list))

In [22]:
Side_effect_encode_list=[]
for a in data_800_1000['Polypharmacy_Side_Effect']:
    b=edgetype_dict[a]
    Side_effect_encode_list.append(b)
data_800_1000['Side_Effect_ID']=Side_effect_encode_list
data_800_1000

C:\Users\Zhouhaifan\.conda\envs\py37\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

,STITCH 1,STITCH 2,Polypharmacy_Side_Effect,Side Effect Name,STITCH_1_ID,STITCH_2_ID,Side_Effect_ID
10,CID000002173,CID000003345,C0038000,rupture of spleen,545,82,"[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
21,CID000002173,CID000003345,C0236124,Gastrointestinal Obstruction,545,82,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
34,CID000002173,CID000003345,C0035220,neonatal respiratory distress syndrome,545,82,"[0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
55,CID000002173,CID000003345,C0013274,patent ductus arteriosis,545,82,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
175,CID000001302,CID000005064,C0155540,ear discharge,181,533,"[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ..."
...,...,...,...,...,...,...,...
4649124,CID000003075,CID000003339,C0341047,parotid gland enlargement,450,194,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4649143,CID000003075,CID000003339,C0040425,tonsillitis,450,194,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4649307,CID000002477,CID000002541,C0020619,hypogonadism,339,17,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4649315,CID000002477,CID000002541,C0003044,animal bite,339,17,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4649387,CID000003461,CID000003954,C0206063,radiation pneumonitis,18,215,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

In [23]:
#修改行名称
index_update1=np.arange(0,132364)
data_800_1000.index=index_update1
data_800_1000

,STITCH 1,STITCH 2,Polypharmacy_Side_Effect,Side Effect Name,STITCH_1_ID,STITCH_2_ID,Side_Effect_ID
0,CID000002173,CID000003345,C0038000,rupture of spleen,545,82,"[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,CID000002173,CID000003345,C0236124,Gastrointestinal Obstruction,545,82,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,CID000002173,CID000003345,C0035220,neonatal respiratory distress syndrome,545,82,"[0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
3,CID000002173,CID000003345,C0013274,patent ductus arteriosis,545,82,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,CID000001302,CID000005064,C0155540,ear discharge,181,533,"[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ..."
...,...,...,...,...,...,...,...
132359,CID000003075,CID000003339,C0341047,parotid gland enlargement,450,194,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
132360,CID000003075,CID000003339,C0040425,tonsillitis,450,194,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
132361,CID000002477,CID000002541,C0020619,hypogonadism,339,17,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
132362,CID000002477,CID000002541,C0003044,animal bite,339,17,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
132363,CID000003461,CID000003954,C0206063,radiation pneumonitis,18,215,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

In [24]:
for i in range(0,132364):
    data_800_1000['Side_Effect_ID'][i]=np.array(data_800_1000['Side_Effect_ID'][i])
data_800_1000

C:\Users\Zhouhaifan\.conda\envs\py37\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,STITCH 1,STITCH 2,Polypharmacy_Side_Effect,Side Effect Name,STITCH_1_ID,STITCH_2_ID,Side_Effect_ID
0,CID000002173,CID000003345,C0038000,rupture of spleen,545,82,"[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,CID000002173,CID000003345,C0236124,Gastrointestinal Obstruction,545,82,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,CID000002173,CID000003345,C0035220,neonatal respiratory distress syndrome,545,82,"[0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
3,CID000002173,CID000003345,C0013274,patent ductus arteriosis,545,82,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,CID000001302,CID000005064,C0155540,ear discharge,181,533,"[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ..."
...,...,...,...,...,...,...,...
132359,CID000003075,CID000003339,C0341047,parotid gland enlargement,450,194,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
132360,CID000003075,CID000003339,C0040425,tonsillitis,450,194,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
132361,CID000002477,CID000002541,C0020619,hypogonadism,339,17,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
132362,CID000002477,CID000002541,C0003044,animal bite,339,17,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
132363,CID000003461,CID000003954,C0206063,radiation pneumonitis,18,215,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

In [25]:
def fun(df):
    #print(df)
    x=np.sum([df],axis=0)
    #print(x)
    x=np.sum(x,axis=0)
    return x
data_800_1000=data_800_1000.groupby(['STITCH_1_ID','STITCH_2_ID'])['Side_Effect_ID'].apply(fun)
data_800_1000 = data_800_1000.reset_index()

In [26]:
data_800_1000

,STITCH_1_ID,STITCH_2_ID,Side_Effect_ID
0,0,86,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,0,98,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,0,99,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
3,0,179,"[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ..."
4,0,254,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
...,...,...,...
34374,618,614,"[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ..."
34375,618,616,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
34376,618,617,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
34377,618,619,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
34378,619,98,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

In [27]:
data_800_1000['Side_Effect_ID'][100]

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
import torch
drug_feature=drug_800_1000['MACCS_fingerprint_int'].to_list()
drug_feature=np.array(drug_feature)
drug_feature=torch.tensor(drug_feature)

In [29]:
drug_feature.size()

torch.Size([620, 167])

In [30]:
STITCH_1_ID_new=data_800_1000['STITCH_1_ID'].to_list()
STITCH_2_ID_new=data_800_1000['STITCH_2_ID'].to_list()
edge_index_new=[STITCH_1_ID_new,STITCH_2_ID_new]
edge_index_new=np.array(edge_index_new)
np.shape(edge_index_new)

(2, 34379)

In [31]:
edge_index_new

array([[  0,   0,   0, ..., 618, 618, 619],
       [ 86,  98,  99, ..., 617, 619,  98]])

In [32]:
edge_index_new=torch.tensor(edge_index_new)
edge_index_new

tensor([[  0,   0,   0,  ..., 618, 618, 619],
        [ 86,  98,  99,  ..., 617, 619,  98]], dtype=torch.int32)

In [33]:
Side_effect_encode_list=data_800_1000['Side_Effect_ID'].to_list()
edge_attr=np.array(Side_effect_encode_list)
edge_attr=torch.tensor(edge_attr)
edge_attr.size()

torch.Size([34379, 200])

In [34]:
from torch_geometric.data import Data
data = Data(x=drug_feature, edge_index=edge_index_new,
                edge_attr=edge_attr)

In [52]:
import pickle
f = open('ddi_800_1000.pckl', 'wb')
pickle.dump(data, f)
f.close()

In [35]:
data_800_1000_compare=pd.read_csv(r'C:\Users\Zhouhaifan\Desktop\GENN-master\data\GENN_seed3_data_800_1000_compare.csv',converters={'Real_DDI_Type': eval,'Predict_DDI_Type': eval})

In [36]:
Real_type_id_list=[]
for i in data_800_1000_compare['Real_DDI_Type']:
    Real_type_id = [j for j,x in enumerate(i) if x==1]
    Real_type_id_list.append(Real_type_id)
data_800_1000_compare['Real_type_id']=Real_type_id_list
data_800_1000_compare

,drug1,drug2,Real_DDI_Type,Predict_DDI_Type,Real_type_id
0,450,240,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0634964257478714, 0.15048401057720184, 0.02...","[44, 48, 49, 52, 73, 95, 100, 104, 112, 158, 1..."
1,192,49,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[2.2681435439153574e-05, 0.008145185187458992,...",[109]
2,364,279,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.031537238508462906, 0.02347353659570217, 0....","[3, 29, 57, 145, 172, 176]"
3,65,184,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.000824739458039403, 0.0027842845302075148, ...",[50]
4,428,566,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0019290331983938813, 0.00472140870988369, 0...",[26]
...,...,...,...,...,...
3433,462,255,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.1345277726650238, 0.0478566437959671, 0.025...","[17, 43, 56, 101]"
3434,462,619,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.006649356801062822, 0.0007117846398614347, ...","[73, 103, 144]"
3435,202,79,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.006043184082955122, 0.0120540177449584, 0.0...",[81]
3436,24,392,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0010244117584079504, 0.0052088783122599125,...",[159]
3437,110,213,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.02044716477394104, 0.016462815925478935, 0....","[3, 89, 112]"

In [37]:
Predict_type_id_list=[]
for i in range(0,3438):
    pre=np.asarray(data_800_1000_compare['Predict_DDI_Type'][i])
    num=len(data_800_1000_compare['Real_type_id'][i])
    Predict_type_id=pre.argsort()[-1:-num-1:-1]
    Predict_type_id_list.append(Predict_type_id)
data_800_1000_compare['Predict_type_id']=Predict_type_id_list
data_800_1000_compare

,drug1,drug2,Real_DDI_Type,Predict_DDI_Type,Real_type_id,Predict_type_id
0,450,240,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0634964257478714, 0.15048401057720184, 0.02...","[44, 48, 49, 52, 73, 95, 100, 104, 112, 158, 1...","[51, 48, 150, 173, 100, 112, 129, 153, 81, 113..."
1,192,49,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[2.2681435439153574e-05, 0.008145185187458992,...",[109],[44]
2,364,279,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.031537238508462906, 0.02347353659570217, 0....","[3, 29, 57, 145, 172, 176]","[142, 177, 57, 99, 64, 176]"
3,65,184,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.000824739458039403, 0.0027842845302075148, ...",[50],[50]
4,428,566,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0019290331983938813, 0.00472140870988369, 0...",[26],[196]
...,...,...,...,...,...,...
3433,462,255,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.1345277726650238, 0.0478566437959671, 0.025...","[17, 43, 56, 101]","[41, 95, 40, 150]"
3434,462,619,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.006649356801062822, 0.0007117846398614347, ...","[73, 103, 144]","[103, 25, 118]"
3435,202,79,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.006043184082955122, 0.0120540177449584, 0.0...",[81],[174]
3436,24,392,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0010244117584079504, 0.0052088783122599125,...",[159],[54]
3437,110,213,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.02044716477394104, 0.016462815925478935, 0....","[3, 89, 112]","[179, 89, 187]"

In [38]:
accuracy_rate_list=[]
for i in range(0,3438):
    real_set=set(data_800_1000_compare['Real_type_id'][i])
    pred_set=set(data_800_1000_compare['Predict_type_id'][i])
    same_number=len(real_set&pred_set)
    accuracy_rate=same_number/len(data_800_1000_compare['Real_type_id'][i])
    accuracy_rate_list.append(accuracy_rate)
data_800_1000_compare['accuracy_rate']=accuracy_rate_list
data_800_1000_compare

,drug1,drug2,Real_DDI_Type,Predict_DDI_Type,Real_type_id,Predict_type_id,accuracy_rate
0,450,240,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0634964257478714, 0.15048401057720184, 0.02...","[44, 48, 49, 52, 73, 95, 100, 104, 112, 158, 1...","[51, 48, 150, 173, 100, 112, 129, 153, 81, 113...",0.250000
1,192,49,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[2.2681435439153574e-05, 0.008145185187458992,...",[109],[44],0.000000
2,364,279,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.031537238508462906, 0.02347353659570217, 0....","[3, 29, 57, 145, 172, 176]","[142, 177, 57, 99, 64, 176]",0.333333
3,65,184,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.000824739458039403, 0.0027842845302075148, ...",[50],[50],1.000000
4,428,566,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0019290331983938813, 0.00472140870988369, 0...",[26],[196],0.000000
...,...,...,...,...,...,...,...
3433,462,255,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.1345277726650238, 0.0478566437959671, 0.025...","[17, 43, 56, 101]","[41, 95, 40, 150]",0.000000
3434,462,619,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.006649356801062822, 0.0007117846398614347, ...","[73, 103, 144]","[103, 25, 118]",0.333333
3435,202,79,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.006043184082955122, 0.0120540177449584, 0.0...",[81],[174],0.000000
3436,24,392,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0010244117584079504, 0.0052088783122599125,...",[159],[54],0.000000
3437,110,213,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.02044716477394104, 0.016462815925478935, 0....","[3, 89, 112]","[179, 89, 187]",0.333333

In [39]:
data_800_1000_compare_sort=data_800_1000_compare.sort_values(by='accuracy_rate',ascending=False)
data_800_1000_compare_sort

,drug1,drug2,Real_DDI_Type,Predict_DDI_Type,Real_type_id,Predict_type_id,accuracy_rate
1577,320,523,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0016582213575020432, 0.09841357171535492, 0...",[46],[46],1.0
329,93,143,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0008097123354673386, 1.462966793042142e-05,...","[40, 41, 174]","[40, 41, 174]",1.0
1330,74,143,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.010090172290802002, 2.3086311557563022e-05,...","[40, 41, 44]","[40, 41, 44]",1.0
806,576,259,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[9.578457684256136e-05, 0.0005304698133841157,...",[90],[90],1.0
2510,307,612,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0035138351377099752, 0.0008049626485444605,...",[100],[100],1.0
...,...,...,...,...,...,...,...
2237,552,420,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.009204881265759468, 0.00019558962958399206,...",[22],[159],0.0
1047,369,7,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.005285528488457203, 0.1094546988606453, 0.2...",[145],[138],0.0
2234,238,317,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.00453175837174058, 0.004607647191733122, 0....",[184],[76],0.0
2233,98,284,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.02047308161854744, 0.016211051493883133, 0....",[144],[149],0.0
1719,1,120,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[8.438267832389101e-05, 0.013011902570724487, ...","[23, 80]","[46, 20]",0.0

In [40]:
data_800_1000_compare_sort.to_excel(r'C:\Users\Zhouhaifan\Desktop\GENN_seed3_data_800_1000_compare_sort.xlsx', index=False)

In [41]:
#修改行名称
index_update2=np.arange(0,3438)
data_800_1000_compare_sort.index=index_update2
data_800_1000_compare_sort

,drug1,drug2,Real_DDI_Type,Predict_DDI_Type,Real_type_id,Predict_type_id,accuracy_rate
0,320,523,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0016582213575020432, 0.09841357171535492, 0...",[46],[46],1.0
1,93,143,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0008097123354673386, 1.462966793042142e-05,...","[40, 41, 174]","[40, 41, 174]",1.0
2,74,143,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.010090172290802002, 2.3086311557563022e-05,...","[40, 41, 44]","[40, 41, 44]",1.0
3,576,259,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[9.578457684256136e-05, 0.0005304698133841157,...",[90],[90],1.0
4,307,612,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0035138351377099752, 0.0008049626485444605,...",[100],[100],1.0
...,...,...,...,...,...,...,...
3433,552,420,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.009204881265759468, 0.00019558962958399206,...",[22],[159],0.0
3434,369,7,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.005285528488457203, 0.1094546988606453, 0.2...",[145],[138],0.0
3435,238,317,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.00453175837174058, 0.004607647191733122, 0....",[184],[76],0.0
3436,98,284,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.02047308161854744, 0.016211051493883133, 0....",[144],[149],0.0
3437,1,120,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[8.438267832389101e-05, 0.013011902570724487, ...","[23, 80]","[46, 20]",0.0

In [42]:
perfect_predict_list=[]
good1=data_800_1000_compare_sort['drug1'][:567].values.tolist()
good2=data_800_1000_compare_sort['drug2'][:567].values.tolist()
good=np.unique(good1+good2)
bad1=data_800_1000_compare_sort['drug1'][567:].values.tolist()
bad2=data_800_1000_compare_sort['drug2'][567:].values.tolist()
bad=np.unique(bad1+bad2)
for i in good:
    if not i in bad:
        perfect_predict_list.append(i)
perfect_predict_list

[25,
 53,
 63,
 64,
 103,
 106,
 136,
 140,
 153,
 158,
 180,
 189,
 195,
 205,
 206,
 258,
 285,
 334,
 355,
 365,
 367,
 379,
 380,
 384,
 425,
 429,
 433,
 453,
 456,
 464,
 501,
 510,
 531,
 550,
 561,
 586,
 608,
 612]

In [43]:
drug_177= [k for k, v in drug_dict.items() if v == 177]
drug_190=[k for k, v in drug_dict.items() if v == 190]
drug_238=[k for k, v in drug_dict.items() if v == 238]
drug_279=[k for k, v in drug_dict.items() if v == 279]
drug_473=[k for k, v in drug_dict.items() if v == 473]
drug_573=[k for k, v in drug_dict.items() if v == 573]
drug_177,drug_190,drug_238,drug_279,drug_473,drug_573

(['CID000145068'],
 ['CID000000838'],
 ['CID000001983'],
 ['CID000004253'],
 ['CID000002142'],
 ['CID000003661'])

In [44]:
edge_df=pd.DataFrame()
edge_df['edgetype_key']=edgetype_key_list
edge_df['edgetype_value']=edgetype_value_list
edge_df

    edgetype_key                                     edgetype_value
0       C0038000  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
1       C0236124  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
2       C0035220  [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
3       C0013274  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
4       C0155540  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...
..           ...                                                ...
195     C0016412  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
196     C0040145  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
197     C0020490  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
198     C0004690  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
199     C0005967  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

[200 rows x 2 columns]

In [45]:
edge_df['edge_type_id']=np.arange(0,200)
edge_df

,edgetype_key,edgetype_value,edge_type_id
0,C0038000,"[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",0
1,C0236124,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1
2,C0035220,"[0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",2
3,C0013274,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",3
4,C0155540,"[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...",4
...,...,...,...
195,C0016412,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",195
196,C0040145,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",196
197,C0020490,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",197
198,C0004690,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",198
199,C0005967,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",199

In [46]:
drug_117_221_real=[9,26,31]
drug_261_13_predict=[ 55 ,5,  69 ,162 , 89 , 32 , 40 , 91 ,182]
for i in range(0,len(drug_117_221_real)):
    drug_117_221_real[i]=edge_df['edgetype_key'][drug_117_221_real[i]]
print(drug_117_221_real)
for i in range(0,len(drug_117_221_real)):
    drug_117_221_real[i]=id_name_dict[drug_117_221_real[i]]
print(drug_117_221_real)

['C0007860', 'C0019917', 'C0003044']
['cervicitis', 'hordeolum', 'animal bite']

In [43]:
drug_117_221_real=[182, 39, 97, 165]
for i in range(0,len(drug_117_221_real)):
    drug_117_221_real[i]=edge_df['edgetype_key'][drug_117_221_real[i]]
print(drug_117_221_real)
for i in range(0,len(drug_117_221_real)):
    drug_117_221_real[i]=id_name_dict[drug_117_221_real[i]]
print(drug_117_221_real)

['C0206504', 'C0002726', 'C0008312', 'C0013369']
['tympanic membrane perforation', 'amyloidosis', 'primary biliary cirrhosis', 'diarrhea infectious']

In [60]:
for i in range(0,len(drug_261_13_predict)):
    drug_261_13_predict[i]=edge_df['edgetype_key'][drug_261_13_predict[i]]
print(drug_261_13_predict)
for i in range(0,len(drug_261_13_predict)):
    drug_261_13_predict[i]=id_name_dict[drug_261_13_predict[i]]
print(drug_261_13_predict)

['C0016479', 'C0151514', 'C0020619', 'C0013274', 'C0270629', 'C0085583', 'C1261473', 'C0262578', 'C0040145']
['food poisoning', 'atrophy of skin', 'hypogonadism', 'patent ductus arteriosis', 'epidural abscess', 'choreoathetosis', 'sarcoma', 'night cramps', 'thyroidectomy']